config/routes.rb
Rails.application.routes.draw do
  get 'service_requests/opensr'
  get 'service_requests/closedsr'
  resources :client_accessories
  resources :server_accessories
  resources :client_records
  resources :switch_ports
  resources :network_switches
  resources :service_requests
  resources :request_statuses
  resources :tech_services
  resources :request_types
  resources :people
  resources :herga_applications
  resources :accessories
  resources :operating_systems
  resources :deployment_statuses
  resources :functional_levels
  resources :server_records
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'static_pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :user
  has_many :server_accessories
  has_many :client_accessories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_accessory.rb
class ClientAccessory < ApplicationRecord
  belongs_to :client_record
  belongs_to :accessory
end

app/models/client_record.rb
class ClientRecord < ApplicationRecord
  belongs_to :person
  belongs_to :user
  belongs_to :operating_system
  has_many   :client_accessories, inverse_of: :client_record
  has_many   :switch_ports

  accepts_nested_attributes_for :client_accessories, allow_destroy: true

end

app/models/deployment_status.rb
class DeploymentStatus < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :herga_applications
end

app/models/functional_level.rb
class FunctionalLevel < ApplicationRecord
  belongs_to :user
  has_many :server_records
end

app/models/herga_application.rb
class HergaApplication < ApplicationRecord
  belongs_to :user
  belongs_to :person
  belongs_to :server_record
  belongs_to :deployment_status
end

app/models/network_switch.rb
class NetworkSwitch < ApplicationRecord
  belongs_to :person
  belongs_to :user
  has_many :switch_ports, inverse_of: :network_switch

  accepts_nested_attributes_for :switch_ports, allow_destroy: true
end

app/models/operating_system.rb
class OperatingSystem < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :client_records
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :herga_applications
  has_many :network_switches
  has_many :client_records
  has_many :server_records
  belongs_to :user
end

app/models/request_status.rb
class RequestStatus < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/server_accessory.rb
class ServerAccessory < ApplicationRecord
  belongs_to :server_record
  belongs_to :accessory
end

app/models/server_record.rb
class ServerRecord < ApplicationRecord
  belongs_to :user
  belongs_to :operating_system
  belongs_to :person
  belongs_to :deployment_status
  belongs_to :functional_level
  has_many   :server_accessories , inverse_of: :server_record
  has_many   :herga_applications
  has_many   :switch_ports


  accepts_nested_attributes_for :server_accessories, allow_destroy: true

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user
  belongs_to :request_status
  belongs_to :request_type
  belongs_to :tech_service

end

app/models/switch_port.rb
class SwitchPort < ApplicationRecord
  belongs_to :user
  belongs_to :network_switch
  belongs_to :server_record
  belongs_to :client_record
end

app/models/tech_service.rb
class TechService < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
  gravtastic

  has_many :server_records
  has_many :herga_applications
  has_many :accessories
  has_many :application_records
  has_many :client_records
  has_many :deployment_statuses
  has_many :functional_levels
  has_many :network_switches
  has_many :operating_systems
  has_many :people
  has_many :request_statuses
  has_many :request_types
  has_many :service_requests
  has_many :switch_ports
  has_many :tech_services



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

    @visitor_view_desc = "Welcome to Techweb.  This application catalogues all computer system hardware and software at Herga Home.
You can also log service issues and request troubleshooting.  Solutions to past technical issues are stored and made available for
future use."

    @notice_of_access_request= "To request access, please contact the systems administrator by email (herga.a@outlook.com) "
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if current_user %>

    <% if current_user.access_granted? %>
      <div class="jumbotron" style="background-color:silver">
        <table class="table table-hover" style="background-color: whitesmoke">
          <thead>
          <tr>
            <th>Modules</th>

          </tr>
          </thead>
          <tbody>
          <tr>
            <td><%= link_to "Server Records", server_records_path %></td>
          </tr>
          <tr>
            <td><%= link_to "Client Records", client_records_path %></td>
          </tr>
          <tr>
            <td><%= link_to "Application Records", herga_applications_path %></td>
          </tr>
          <tr>
            <td><%= link_to "Network Switches Connections", network_switches_path %></td>
          </tr>
          <tr>
            <td><%= link_to "Open Service Requests", service_requests_opensr_path %></td>
          </tr>
          <tr>
            <td><%= link_to "Closed Service Requests", service_requests_closedsr_path %></td>
          </tr>

          <% if current_user.admin? %>
            <tr>
              <td><%= link_to "All Service Requests", service_requests_path %></td>
              <td> </td>
            </tr>
          <% end %>

          </tbody>
        </table>
      </div>

  <% else %>
    <div class="alert-danger">Your Access Request is currently under review.  Please contact the system administrator
      for more information.
    </div>
  <% end  %>


<% else %>

  <div class="jumbotron" style="background-color: #2a4b51">
    <div class="breadcrumb" style="background-color: khaki">
      <h2>Techweb</h2>
    </div>
    <div class="jumbotron">
      <%= @visitor_view_desc %>
    </div>

    <div class="breadcrumb" style="background-color: khaki; color: #730E15">
      <%= @notice_of_access_request %>
    </div>

  <% end %>




  </div>