config/routes.rb
Rails.application.routes.draw do
  get 'service_requests/opensr'
  get 'service_requests/closedsr'
  resources :client_accessories
  resources :server_accessories
  resources :client_records
  resources :switch_ports
  resources :network_switches
  resources :service_requests
  resources :request_statuses
  resources :tech_services
  resources :request_types
  resources :people
  resources :herga_applications
  resources :accessories
  resources :operating_systems
  resources :deployment_statuses
  resources :functional_levels
  resources :server_records
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'static_pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :user
  has_many :server_accessories
  has_many :client_accessories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_accessory.rb
class ClientAccessory < ApplicationRecord
  belongs_to :client_record
  belongs_to :accessory
end

app/models/client_record.rb
class ClientRecord < ApplicationRecord
  belongs_to :person
  belongs_to :user
  belongs_to :operating_system
  has_many   :client_accessories, inverse_of: :client_record
  has_many   :switch_ports

  accepts_nested_attributes_for :client_accessories, allow_destroy: true

end

app/models/deployment_status.rb
class DeploymentStatus < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :herga_applications
end

app/models/functional_level.rb
class FunctionalLevel < ApplicationRecord
  belongs_to :user
  has_many :server_records
end

app/models/herga_application.rb
class HergaApplication < ApplicationRecord
  belongs_to :user
  belongs_to :person
  belongs_to :server_record
  belongs_to :deployment_status
end

app/models/network_switch.rb
class NetworkSwitch < ApplicationRecord
  belongs_to :person
  belongs_to :user
  has_many :switch_ports, inverse_of: :network_switch

  accepts_nested_attributes_for :switch_ports, allow_destroy: true
end

app/models/operating_system.rb
class OperatingSystem < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :client_records
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :herga_applications
  has_many :network_switches
  has_many :client_records
  has_many :server_records
  belongs_to :user
end

app/models/request_status.rb
class RequestStatus < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/server_accessory.rb
class ServerAccessory < ApplicationRecord
  belongs_to :server_record
  belongs_to :accessory
end

app/models/server_record.rb
class ServerRecord < ApplicationRecord
  belongs_to :user
  belongs_to :operating_system
  belongs_to :person
  belongs_to :deployment_status
  belongs_to :functional_level
  has_many   :server_accessories , inverse_of: :server_record
  has_many   :herga_applications
  has_many   :switch_ports


  accepts_nested_attributes_for :server_accessories, allow_destroy: true

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user
  belongs_to :request_status
  belongs_to :request_type
  belongs_to :tech_service

end

app/models/switch_port.rb
class SwitchPort < ApplicationRecord
  belongs_to :user
  belongs_to :network_switch
  belongs_to :server_record
  belongs_to :client_record
end

app/models/tech_service.rb
class TechService < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
  gravtastic

  has_many :server_records
  has_many :herga_applications
  has_many :accessories
  has_many :application_records
  has_many :client_records
  has_many :deployment_statuses
  has_many :functional_levels
  has_many :network_switches
  has_many :operating_systems
  has_many :people
  has_many :request_statuses
  has_many :request_types
  has_many :service_requests
  has_many :switch_ports
  has_many :tech_services



end

app/controllers/switch_ports_controller.rb
class SwitchPortsController < ApplicationController
  before_action :set_switch_port, only: [:show, :edit, :update, :destroy]

  # GET /switch_ports
  # GET /switch_ports.json
  def index
    @switch_ports = SwitchPort.all
  end

  # GET /switch_ports/1
  # GET /switch_ports/1.json
  def show
  end

  # GET /switch_ports/new
  def new
    @switch_port = SwitchPort.new
  end

  # GET /switch_ports/1/edit
  def edit
  end

  # POST /switch_ports
  # POST /switch_ports.json
  def create
    @switch_port = SwitchPort.new(switch_port_params)

    respond_to do |format|
      if @switch_port.save
        format.html { redirect_to @switch_port, notice: 'Switch port was successfully created.' }
        format.json { render :show, status: :created, location: @switch_port }
      else
        format.html { render :new }
        format.json { render json: @switch_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /switch_ports/1
  # PATCH/PUT /switch_ports/1.json
  def update
    respond_to do |format|
      if @switch_port.update(switch_port_params)
        format.html { redirect_to @switch_port, notice: 'Switch port was successfully updated.' }
        format.json { render :show, status: :ok, location: @switch_port }
      else
        format.html { render :edit }
        format.json { render json: @switch_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /switch_ports/1
  # DELETE /switch_ports/1.json
  def destroy
    @switch_port.destroy
    respond_to do |format|
      format.html { redirect_to switch_ports_url, notice: 'Switch port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_switch_port
      @switch_port = SwitchPort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def switch_port_params
      params.require(:switch_port).permit(:network_switch_id, :port_number, :server_record_id, :client_record_id, :notes, :user_id)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Techweb"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/switch_ports_helper.rb
module SwitchPortsHelper
end

app/views/switch_ports/_form.html.erb
<%= form_with(model: switch_port, local: true) do |form| %>
  <% if switch_port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(switch_port.errors.count, "error") %> prohibited this switch_port from being saved:</h2>

      <ul>
      <% switch_port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :network_switch_id %>
    <%= form.number_field :network_switch_id %>
  </div>

  <div class="field">
    <%= form.label :port_number %>
    <%= form.number_field :port_number %>
  </div>

  <div class="field">
    <%= form.label :server_record_id %>
    <%= form.number_field :server_record_id %>
  </div>

  <div class="field">
    <%= form.label :client_record_id %>
    <%= form.number_field :client_record_id %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/switch_ports/edit.html.erb
<h1>Editing Switch Port</h1>

<%= render 'form', switch_port: @switch_port %>

<%= link_to 'Show', @switch_port %> |
<%= link_to 'Back', switch_ports_path %>

app/views/switch_ports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Switch Ports</h1>

<table>
  <thead>
    <tr>
      <th>Network switch</th>
      <th>Port number</th>
      <th>Server record</th>
      <th>Client record</th>
      <th>Notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @switch_ports.each do |switch_port| %>
      <tr>
        <td><%= switch_port.network_switch_id %></td>
        <td><%= switch_port.port_number %></td>
        <td><%= switch_port.server_record_id %></td>
        <td><%= switch_port.client_record_id %></td>
        <td><%= switch_port.notes %></td>
        <td><%= switch_port.user_id %></td>
        <td><%= link_to 'Show', switch_port %></td>
        <td><%= link_to 'Edit', edit_switch_port_path(switch_port) %></td>
        <td><%= link_to 'Destroy', switch_port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Switch Port', new_switch_port_path %>

app/views/switch_ports/new.html.erb
<h1>New Switch Port</h1>

<%= render 'form', switch_port: @switch_port %>

<%= link_to 'Back', switch_ports_path %>

app/views/switch_ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Network switch:</strong>
  <%= @switch_port.network_switch_id %>
</p>

<p>
  <strong>Port number:</strong>
  <%= @switch_port.port_number %>
</p>

<p>
  <strong>Server record:</strong>
  <%= @switch_port.server_record_id %>
</p>

<p>
  <strong>Client record:</strong>
  <%= @switch_port.client_record_id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @switch_port.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @switch_port.user_id %>
</p>

<%= link_to 'Edit', edit_switch_port_path(@switch_port) %> |
<%= link_to 'Back', switch_ports_path %>