config/routes.rb
Rails.application.routes.draw do
  get 'service_requests/opensr'
  get 'service_requests/closedsr'
  resources :client_accessories
  resources :server_accessories
  resources :client_records
  resources :switch_ports
  resources :network_switches
  resources :service_requests
  resources :request_statuses
  resources :tech_services
  resources :request_types
  resources :people
  resources :herga_applications
  resources :accessories
  resources :operating_systems
  resources :deployment_statuses
  resources :functional_levels
  resources :server_records
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'static_pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :user
  has_many :server_accessories
  has_many :client_accessories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_accessory.rb
class ClientAccessory < ApplicationRecord
  belongs_to :client_record
  belongs_to :accessory
end

app/models/client_record.rb
class ClientRecord < ApplicationRecord
  belongs_to :person
  belongs_to :user
  belongs_to :operating_system
  has_many   :client_accessories, inverse_of: :client_record
  has_many   :switch_ports

  accepts_nested_attributes_for :client_accessories, allow_destroy: true

end

app/models/deployment_status.rb
class DeploymentStatus < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :herga_applications
end

app/models/functional_level.rb
class FunctionalLevel < ApplicationRecord
  belongs_to :user
  has_many :server_records
end

app/models/herga_application.rb
class HergaApplication < ApplicationRecord
  belongs_to :user
  belongs_to :person
  belongs_to :server_record
  belongs_to :deployment_status
end

app/models/network_switch.rb
class NetworkSwitch < ApplicationRecord
  belongs_to :person
  belongs_to :user
  has_many :switch_ports, inverse_of: :network_switch

  accepts_nested_attributes_for :switch_ports, allow_destroy: true
end

app/models/operating_system.rb
class OperatingSystem < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :client_records
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :herga_applications
  has_many :network_switches
  has_many :client_records
  has_many :server_records
  belongs_to :user
end

app/models/request_status.rb
class RequestStatus < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/server_accessory.rb
class ServerAccessory < ApplicationRecord
  belongs_to :server_record
  belongs_to :accessory
end

app/models/server_record.rb
class ServerRecord < ApplicationRecord
  belongs_to :user
  belongs_to :operating_system
  belongs_to :person
  belongs_to :deployment_status
  belongs_to :functional_level
  has_many   :server_accessories , inverse_of: :server_record
  has_many   :herga_applications
  has_many   :switch_ports


  accepts_nested_attributes_for :server_accessories, allow_destroy: true

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user
  belongs_to :request_status
  belongs_to :request_type
  belongs_to :tech_service

end

app/models/switch_port.rb
class SwitchPort < ApplicationRecord
  belongs_to :user
  belongs_to :network_switch
  belongs_to :server_record
  belongs_to :client_record
end

app/models/tech_service.rb
class TechService < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
  gravtastic

  has_many :server_records
  has_many :herga_applications
  has_many :accessories
  has_many :application_records
  has_many :client_records
  has_many :deployment_statuses
  has_many :functional_levels
  has_many :network_switches
  has_many :operating_systems
  has_many :people
  has_many :request_statuses
  has_many :request_types
  has_many :service_requests
  has_many :switch_ports
  has_many :tech_services



end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < ApplicationController
  before_action :set_operating_system, only: [:show, :edit, :update, :destroy]

  # GET /operating_systems
  # GET /operating_systems.json
  def index
    @operating_systems = OperatingSystem.all
  end

  # GET /operating_systems/1
  # GET /operating_systems/1.json
  def show
  end

  # GET /operating_systems/new
  def new
    @operating_system = OperatingSystem.new
  end

  # GET /operating_systems/1/edit
  def edit
  end

  # POST /operating_systems
  # POST /operating_systems.json
  def create
    @operating_system = OperatingSystem.new(operating_system_params)

    respond_to do |format|
      if @operating_system.save
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully created.' }
        format.json { render :show, status: :created, location: @operating_system }
      else
        format.html { render :new }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operating_systems/1
  # PATCH/PUT /operating_systems/1.json
  def update
    respond_to do |format|
      if @operating_system.update(operating_system_params)
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully updated.' }
        format.json { render :show, status: :ok, location: @operating_system }
      else
        format.html { render :edit }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operating_systems/1
  # DELETE /operating_systems/1.json
  def destroy
    @operating_system.destroy
    respond_to do |format|
      format.html { redirect_to operating_systems_url, notice: 'Operating system was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operating_system
      @operating_system = OperatingSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operating_system_params
      params.require(:operating_system).permit(:name, :description, :active, :notes, :user_id)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Techweb"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/operating_systems/_form.html.erb
<%= form_with(model: operating_system, local: true) do |form| %>
  <% if operating_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operating_system.errors.count, "error") %> prohibited this operating_system from being saved:</h2>

      <ul>
      <% operating_system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/operating_systems/edit.html.erb
<h1>Editing Operating System</h1>

<%= render 'form', operating_system: @operating_system %>

<%= link_to 'Show', @operating_system %> |
<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operating Systems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th>Notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operating_systems.each do |operating_system| %>
      <tr>
        <td><%= operating_system.name %></td>
        <td><%= operating_system.description %></td>
        <td><%= operating_system.active %></td>
        <td><%= operating_system.notes %></td>
        <td><%= operating_system.user_id %></td>
        <td><%= link_to 'Show', operating_system %></td>
        <td><%= link_to 'Edit', edit_operating_system_path(operating_system) %></td>
        <td><%= link_to 'Destroy', operating_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operating System', new_operating_system_path %>

app/views/operating_systems/new.html.erb
<h1>New Operating System</h1>

<%= render 'form', operating_system: @operating_system %>

<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @operating_system.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @operating_system.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @operating_system.active %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @operating_system.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @operating_system.user_id %>
</p>

<%= link_to 'Edit', edit_operating_system_path(@operating_system) %> |
<%= link_to 'Back', operating_systems_path %>