config/routes.rb
Rails.application.routes.draw do
  get 'service_requests/opensr'
  get 'service_requests/closedsr'
  resources :client_accessories
  resources :server_accessories
  resources :client_records
  resources :switch_ports
  resources :network_switches
  resources :service_requests
  resources :request_statuses
  resources :tech_services
  resources :request_types
  resources :people
  resources :herga_applications
  resources :accessories
  resources :operating_systems
  resources :deployment_statuses
  resources :functional_levels
  resources :server_records
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'static_pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :user
  has_many :server_accessories
  has_many :client_accessories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_accessory.rb
class ClientAccessory < ApplicationRecord
  belongs_to :client_record
  belongs_to :accessory
end

app/models/client_record.rb
class ClientRecord < ApplicationRecord
  belongs_to :person
  belongs_to :user
  belongs_to :operating_system
  has_many   :client_accessories, inverse_of: :client_record
  has_many   :switch_ports

  accepts_nested_attributes_for :client_accessories, allow_destroy: true

end

app/models/deployment_status.rb
class DeploymentStatus < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :herga_applications
end

app/models/functional_level.rb
class FunctionalLevel < ApplicationRecord
  belongs_to :user
  has_many :server_records
end

app/models/herga_application.rb
class HergaApplication < ApplicationRecord
  belongs_to :user
  belongs_to :person
  belongs_to :server_record
  belongs_to :deployment_status
end

app/models/network_switch.rb
class NetworkSwitch < ApplicationRecord
  belongs_to :person
  belongs_to :user
  has_many :switch_ports, inverse_of: :network_switch

  accepts_nested_attributes_for :switch_ports, allow_destroy: true
end

app/models/operating_system.rb
class OperatingSystem < ApplicationRecord
  belongs_to :user
  has_many :server_records
  has_many :client_records
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :herga_applications
  has_many :network_switches
  has_many :client_records
  has_many :server_records
  belongs_to :user
end

app/models/request_status.rb
class RequestStatus < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/server_accessory.rb
class ServerAccessory < ApplicationRecord
  belongs_to :server_record
  belongs_to :accessory
end

app/models/server_record.rb
class ServerRecord < ApplicationRecord
  belongs_to :user
  belongs_to :operating_system
  belongs_to :person
  belongs_to :deployment_status
  belongs_to :functional_level
  has_many   :server_accessories , inverse_of: :server_record
  has_many   :herga_applications
  has_many   :switch_ports


  accepts_nested_attributes_for :server_accessories, allow_destroy: true

end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user
  belongs_to :request_status
  belongs_to :request_type
  belongs_to :tech_service

end

app/models/switch_port.rb
class SwitchPort < ApplicationRecord
  belongs_to :user
  belongs_to :network_switch
  belongs_to :server_record
  belongs_to :client_record
end

app/models/tech_service.rb
class TechService < ApplicationRecord
  belongs_to :user
  has_many :service_requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
  gravtastic

  has_many :server_records
  has_many :herga_applications
  has_many :accessories
  has_many :application_records
  has_many :client_records
  has_many :deployment_statuses
  has_many :functional_levels
  has_many :network_switches
  has_many :operating_systems
  has_many :people
  has_many :request_statuses
  has_many :request_types
  has_many :service_requests
  has_many :switch_ports
  has_many :tech_services



end

app/controllers/network_switches_controller.rb
class NetworkSwitchesController < ApplicationController
  before_action :set_network_switch, only: [:show, :edit, :update, :destroy]

  # GET /network_switches
  # GET /network_switches.json
  def index
    @network_switches = NetworkSwitch.all
  end

  # GET /network_switches/1
  # GET /network_switches/1.json
  def show

  end

  # GET /network_switches/new
  def new
    @network_switch = NetworkSwitch.new
  end

  # GET /network_switches/1/edit
  def edit
  end

  # POST /network_switches
  # POST /network_switches.json
  def create
    @network_switch = NetworkSwitch.new(network_switch_params)

    respond_to do |format|
      if @network_switch.save
        format.html { redirect_to @network_switch, notice: 'Network switch was successfully created.' }
        format.json { render :show, status: :created, location: @network_switch }
      else
        format.html { render :new }
        format.json { render json: @network_switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /network_switches/1
  # PATCH/PUT /network_switches/1.json
  def update
    respond_to do |format|
      if @network_switch.update(network_switch_params)
        format.html { redirect_to @network_switch, notice: 'Network switch was successfully updated.' }
        format.json { render :show, status: :ok, location: @network_switch }
      else
        format.html { render :edit }
        format.json { render json: @network_switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /network_switches/1
  # DELETE /network_switches/1.json
  def destroy
    @network_switch.destroy
    respond_to do |format|
      format.html { redirect_to network_switches_url, notice: 'Network switch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network_switch
      @network_switch = NetworkSwitch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_switch_params
      params.require(:network_switch).permit(:code_name, :branding, :number_of_ports, :s_location, :ip_address,
                                             :user_name, :password, :active, :notes, :user_id,
                                             :person_id,switch_ports_attributes:[:id, :port_number,:server_record_id,
                                                                                 :client_record_id,:notes,:user_id,:_destroy])
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Techweb"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/network_switches_helper.rb
module NetworkSwitchesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/network_switches/_form.html.erb
<%= simple_form_for(@network_switch, html: { class: 'form' }) do |f| %>
  <% if network_switch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(network_switch.errors.count, "error") %> prohibited this network_switch from being saved:</h2>

      <ul>
      <% network_switch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="jumbotron" style="background-color: silver">

    <div class="row">
      <div class="col-sm-4">
        <%= f.input :code_name %>
        <%= f.input :branding %>
        <%= f.input :number_of_ports %>
        <%= f.input :s_location, label: "Switch Location" %>
      </div>
      <div class="col-sm-4">
        <%= f.input :ip_address %>
        <%= f.input :user_name %>
        <%= f.input :password %>
        <%= f.input :active %>
      </div>
      <div class="col-sm-4">
        <%= f.input :user_id, :as =>  :hidden,input_html: {value:current_user.id} %>
        <%= f.association :person, collection: Person.order(:fullname),label_method: :fullname,
                          prompt: "Select", label:"Owner" %>
        <%= f.input :notes %>
      </div>
    </div>

    <div class="breadcrumb" style="background-color: gray">
      <%= f.button :submit, "Save" %>
    </div>

  </div>


  <div class="jumbotron" style="background-color: lightgrey">

    <div class="breadcrumb" style="background-color: darkgrey">
      Client Accessories
    </div>

    <div class="nested_fields">

      <%= f.simple_fields_for :switch_ports do |port| %>
        <div class="jumbotron">
          <%= render 'switch_port_fields', :f => port %>
        </div>
      <% end %>
      <br>
      <div class="breadcrumb">
        <%= link_to_add_association 'Add', f, :switch_ports, class: 'fa fa-plus',style:"font-size:15px;color:green"%>
      </div>
    </div>
    <hr/>
  </div>

  <div class="breadcrumb" style="background-color: silver">
    <%= f.button :submit, "Save" %>
  </div>

<% end %>

app/views/network_switches/_switch_port_fields.html.erb
<div class="nested-fields">
  <div class="jumbotron" style="background-color: silver">
    <div class="form-inputs">


      <%= f.input :port_number %>

      <%= f.input :user_id, :as =>  :hidden,input_html: {value:current_user.id} %>

      <div class="control-group">
        <div class ="controls">

          <%= f.association :server_record, collection: ServerRecord.order(:name),label_method: :name, prompt: "Select", label:"Server" %>
        </div>
      </div>
      <br>

      <div class="control-group">
        <div class ="controls">

          <%= f.association :client_record, collection: ClientRecord.order(:name),label_method: :name, prompt: "Select", label:"Client" %>
        </div>
      </div>
      <br>
      <%= f.input :notes %>
    </div>
    <hr>
    <div class="breadcrumb">
      <%= link_to_remove_association 'Remove', f ,class: 'fa fa-close', style:"font-size:15px;color:red"%>
    </div>
  </div>
</div>

app/views/network_switches/edit.html.erb
<% provide(:title, "Edit") %>
<div class="breadcrumb" style="background-color: darkblue;color:whitesmoke">
  <h5>Editing Network Switch</h5>
</div>


<%= render 'form', network_switch: @network_switch %>


<div class="breadcrumb">
  <%= link_to 'View', @network_switch %> |
  <%= link_to 'Back', network_switches_path %>
</div>

app/views/network_switches/index.html.erb
<% provide(:title, "Servers") %>

<div class="breadcrumb" style="background-color: darkblue;color:whitesmoke">
  <h5>Network Switches</h5>
</div>


<div class="jumbotron"style=" background-color:silver ">
  <table class="table table-bordered" style="background-color: white">
    <thead>
    <tr>
      <th>Code name</th>
      <th>Branding</th>
      <th>Number of ports</th>
      <th>Ip address</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @network_switches.each do |network_switch| %>
      <tr>
        <td><%= network_switch.code_name %></td>
        <td><%= network_switch.branding %></td>
        <td><%= network_switch.number_of_ports %></td>
        <td><%= network_switch.ip_address %></td>
        <td><%= network_switch.active.humanize %></td>
        <td><%= link_to 'View', network_switch %></td>
        <td><%= link_to 'Edit', edit_network_switch_path(network_switch) %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Delete', network_switch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>
  <div class="breadcrumb">
    <%= link_to 'New Network Switch', new_network_switch_path %>
  </div>
</div>

app/views/network_switches/new.html.erb
<% provide(:title, "New") %>

<div class="breadcrumb" style="background-color: darkblue;color:whitesmoke">
  <h5>New Network Switch</h5>
</div>


<%= render 'form', network_switch: @network_switch %>

<div class="breadcrumb">
  <%= link_to 'Back', network_switches_path %>
</div>

app/views/network_switches/show.html.erb
<% provide(:title, "Net SWitch") %>


<div class="breadcrumb" style="background-color: navy;color: white">
  <h4> Ref#: <%= @network_switch.id %> | <%= @network_switch.code_name %> </h4>
</div>


<div class="jumbotron" style="background-color: silver;color: black">
  <table class="table table-bordered" style="background-color: whitesmoke">
    <tbody>
    <tr>
      <td>Code name:</td>
      <td>  <%= @network_switch.code_name %> </td>
    </tr>
    <tr>
      <td>Branding:</td>
      <td> <%= @network_switch.branding %></td>
    </tr>
    <tr>
      <td>Number of ports:</td>
      <td><%= @network_switch.number_of_ports %></td>
    </tr>
    <tr>
      <td>Swicth location:</td>
      <td><%= @network_switch.s_location %></td>
    </tr>
    <tr>
      <td>Ip address:</td>
      <td><%= @network_switch.ip_address %></td>
    </tr>
    <tr>
      <td>User name:</td>
      <td><<%= @network_switch.user_name %></td>
    </tr>
    <tr>
      <td>Password:</td>
      <td><%= @network_switch.password %></td>
    </tr>
    <tr>
      <td>Active:</td>
      <td><%= @network_switch.active.humanize %></td>
    </tr>
    <tr>
      <td>Notes:</td>
      <td>  <%= @network_switch.notes %></td>
    </tr>
    <tr>
      <td> Record created by:</td>
      <td><%= @network_switch.user.fullname %></td>
    </tr>
    <tr>
      <td>Owned By:</td>
      <td><%= @network_switch.person.fullname %></td>
    </tr>

    </tbody>
  </table>

  <div class="breadcrumb">
    <%= link_to 'Edit', edit_network_switch_path(@network_switch) %> |
    <%= link_to 'Back', network_switches_path %>
  </div>
</div>

<div class="jumbotron" style="background-color: silver">
  <div class="breadcrumb", style="background-color: darkgrey">
    Related Port Connections
  </div>

  <table class="table table-bordered" style="background-color: white;color: black">
    <thead>
    <tr>
      <th>Port Number</th>
      <th>Server</th>
      <th>client</th>
      <th>Notes</th>

      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% for port in @network_switch.switch_ports %>
      <tr>
        <td><%= port.port_number %></td>
        <td><%= port.server_record.name %></td>
        <td><%= port.client_record.name %></td>
        <td><%= port.notes %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="breadcrumb">
    <%= link_to 'Edit', edit_network_switch_path(@network_switch) %> |
    <%= link_to 'Back', network_switches_path %>

  </div>

</div>